### PR TITLE
[WIP] JAX port

### PR DESCRIPTION
**Pull request by cgarciae**
Hey, I am really enjoying the tutorials, thanks for creating this! 

I started porting them to JAX, mostly to get a chance to re-implement it an learn a bit more, and wanted to contribute back if you are interested in this.

### CODE REVIEW

**Comment by cgarciae** [comment]
So far I've only done half of the first notebook, the only major deviation is that I've added animations of the processes:

**Comment by esling** [comment]
Hey @cgarciae, wow thank you so much, this looks great ! I am looking forward to your JAX port, even though I have zero knowledge on this framework 😄. Hopefully, i will try to extend the tutorials with the latest developments on diffusion

**Comment by cgarciae** [comment]
Hey @esling! Eager to see the new material.
Glad you liked it :)
I will send a new PR with the continuation of this.

BTW: In the open source world a `[WIP]` tag means "Work In Progress" which is usually used for an ongoing effort that is published mostly so that others can comment on but its not meant to be merge yet 😅

**Comment by esling** [comment]
Ahah sorry @cgarciae, guess I got way too excited about that ^^

**Pull request merged**
